export const LEAGUES = {
  NBA: 'NBA',
  EPL: 'EPL',
  AFL: 'AFL',
  WC: 'WC',
  LALIGA: 'LALIGA',
  BUNDESLIGA: 'BUNDESLIGA',
  SERIEA: 'SERIEA',
  LIGUE1: 'LIGUE1',
  CHAMPIONSHIP: 'CHAMPIONSHIP',
  EREDIVISIE: 'EREDIVISIE',
  UCL: 'UCL',
  NFL: 'NFL',
  NHL: 'NHL',
  MLB: 'MLB',
  NRL: 'NRL',
  WNBA: 'WNBA',
  NWSL: 'NWSL',
  ALEAGUE: 'ALEAGUE',
  LIGAMX: 'LIGAMX',
  BRASILEIRAO: 'BRASILEIRAO',
  ARGENTINA: 'ARGENTINA',
  SAUDIPL: 'SAUDIPL',
  PRIMEIRALIGA: 'PRIMEIRALIGA',
  TURKEY: 'TURKEY',
  SCOTLAND: 'SCOTLAND',
  JLEAGUE: 'JLEAGUE',
  BELGIUM: 'BELGIUM',
  IPL: 'IPL',
  BBL: 'BBL',
};

export const SUPPORTED_LEAGUES = Object.values(LEAGUES);

export const LEAGUE_DISPLAY_NAMES = {
  NBA: 'NBA',
  EPL: 'Premier League',
  AFL: 'AFL',
  WC: 'World Cup',
  LALIGA: 'La Liga',
  BUNDESLIGA: 'Bundesliga',
  SERIEA: 'Serie A',
  LIGUE1: 'Ligue 1',
  CHAMPIONSHIP: 'Championship',
  EREDIVISIE: 'Eredivisie',
  UCL: 'Champions League',
  NFL: 'NFL',
  NHL: 'NHL',
  MLB: 'MLB',
  NRL: 'NRL',
  WNBA: 'WNBA',
  NWSL: 'NWSL',
  ALEAGUE: 'A-League',
  LIGAMX: 'Liga MX',
  BRASILEIRAO: 'Brasileirão',
  ARGENTINA: 'Liga Profesional',
  SAUDIPL: 'Saudi Pro League',
  PRIMEIRALIGA: 'Primeira Liga',
  TURKEY: 'Süper Lig',
  SCOTLAND: 'Scottish Premiership',
  JLEAGUE: 'J1 League',
  BELGIUM: 'Belgian Pro League',
  IPL: 'IPL',
  BBL: 'Big Bash League',
};

// Short forms for tight spaces (e.g. the team logo strip's per-league sub-labels)
export const LEAGUE_ABBR = {
  NBA: 'NBA',
  EPL: 'EPL',
  AFL: 'AFL',
  WC: 'World Cup',
  LALIGA: 'La Liga',
  BUNDESLIGA: 'Bundesliga',
  SERIEA: 'Serie A',
  LIGUE1: 'Ligue 1',
  CHAMPIONSHIP: 'Championship',
  EREDIVISIE: 'Eredivisie',
  UCL: 'UCL',
  NFL: 'NFL',
  NHL: 'NHL',
  MLB: 'MLB',
  NRL: 'NRL',
  WNBA: 'WNBA',
  NWSL: 'NWSL',
  ALEAGUE: 'A-League',
  LIGAMX: 'Liga MX',
  BRASILEIRAO: 'Brasileirão',
  ARGENTINA: 'Liga Prof.',
  SAUDIPL: 'Saudi PL',
  PRIMEIRALIGA: 'Primeira Liga',
  TURKEY: 'Süper Lig',
  SCOTLAND: 'Scot. Prem.',
  JLEAGUE: 'J1 League',
  BELGIUM: 'Pro League',
  IPL: 'IPL',
  BBL: 'Big Bash',
};

// Groups the many soccer competitions under one heading; each other league is its own sport
export const SPORTS = {
  BASKETBALL: 'BASKETBALL',
  SOCCER: 'SOCCER',
  AFL: 'AFL',
  GRIDIRON: 'GRIDIRON',
  HOCKEY: 'HOCKEY',
  BASEBALL: 'BASEBALL',
  RUGBY_LEAGUE: 'RUGBY_LEAGUE',
  CRICKET: 'CRICKET',
};

export const LEAGUE_SPORT = {
  NBA: SPORTS.BASKETBALL,
  EPL: SPORTS.SOCCER,
  WC: SPORTS.SOCCER,
  LALIGA: SPORTS.SOCCER,
  BUNDESLIGA: SPORTS.SOCCER,
  SERIEA: SPORTS.SOCCER,
  LIGUE1: SPORTS.SOCCER,
  CHAMPIONSHIP: SPORTS.SOCCER,
  EREDIVISIE: SPORTS.SOCCER,
  UCL: SPORTS.SOCCER,
  AFL: SPORTS.AFL,
  NFL: SPORTS.GRIDIRON,
  NHL: SPORTS.HOCKEY,
  MLB: SPORTS.BASEBALL,
  NRL: SPORTS.RUGBY_LEAGUE,
  // Shares NBA's sport bucket rather than getting its own — same sport, same icon.
  WNBA: SPORTS.BASKETBALL,
  // All eleven share the soccer bucket with EPL/La Liga/etc. — same sport, same icon.
  NWSL: SPORTS.SOCCER,
  ALEAGUE: SPORTS.SOCCER,
  LIGAMX: SPORTS.SOCCER,
  BRASILEIRAO: SPORTS.SOCCER,
  ARGENTINA: SPORTS.SOCCER,
  SAUDIPL: SPORTS.SOCCER,
  PRIMEIRALIGA: SPORTS.SOCCER,
  TURKEY: SPORTS.SOCCER,
  SCOTLAND: SPORTS.SOCCER,
  JLEAGUE: SPORTS.SOCCER,
  BELGIUM: SPORTS.SOCCER,
  IPL: SPORTS.CRICKET,
  BBL: SPORTS.CRICKET,
};

export const SPORT_DISPLAY_NAMES = {
  BASKETBALL: 'Basketball',
  SOCCER: 'Soccer',
  AFL: 'AFL',
  GRIDIRON: 'NFL',
  HOCKEY: 'NHL',
  BASEBALL: 'MLB',
  RUGBY_LEAGUE: 'NRL',
  CRICKET: 'Cricket',
};

// Groups leagues by continent/region for the favourites menu's league list —
// separate from SPORTS above, which groups by sport instead (used for the
// dashboard's team strip). WC (World Cup) is international rather than
// belonging to one continent; UCL is nominally pan-European but every club
// in it is European, so it sits with the rest of Europe rather than its own
// bucket. Mexico (LIGAMX) is grouped with North America (CONCACAF), matching
// how it's usually categorised in football.
export const REGIONS = {
  INTERNATIONAL: 'INTERNATIONAL',
  NORTH_AMERICA: 'NORTH_AMERICA',
  SOUTH_AMERICA: 'SOUTH_AMERICA',
  EUROPE: 'EUROPE',
  ASIA: 'ASIA',
  OCEANIA: 'OCEANIA',
};

export const REGION_DISPLAY_NAMES = {
  INTERNATIONAL: 'International',
  NORTH_AMERICA: 'North America',
  SOUTH_AMERICA: 'South America',
  EUROPE: 'Europe',
  ASIA: 'Asia',
  OCEANIA: 'Oceania',
};

// Display order when grouping the leagues UI by region.
export const REGION_ORDER = [
  REGIONS.INTERNATIONAL,
  REGIONS.NORTH_AMERICA,
  REGIONS.SOUTH_AMERICA,
  REGIONS.EUROPE,
  REGIONS.ASIA,
  REGIONS.OCEANIA,
];

export const LEAGUE_REGION = {
  WC: REGIONS.INTERNATIONAL,
  NBA: REGIONS.NORTH_AMERICA,
  NFL: REGIONS.NORTH_AMERICA,
  NHL: REGIONS.NORTH_AMERICA,
  MLB: REGIONS.NORTH_AMERICA,
  WNBA: REGIONS.NORTH_AMERICA,
  NWSL: REGIONS.NORTH_AMERICA,
  LIGAMX: REGIONS.NORTH_AMERICA,
  ARGENTINA: REGIONS.SOUTH_AMERICA,
  BRASILEIRAO: REGIONS.SOUTH_AMERICA,
  EPL: REGIONS.EUROPE,
  LALIGA: REGIONS.EUROPE,
  BUNDESLIGA: REGIONS.EUROPE,
  SERIEA: REGIONS.EUROPE,
  LIGUE1: REGIONS.EUROPE,
  CHAMPIONSHIP: REGIONS.EUROPE,
  EREDIVISIE: REGIONS.EUROPE,
  UCL: REGIONS.EUROPE,
  PRIMEIRALIGA: REGIONS.EUROPE,
  TURKEY: REGIONS.EUROPE,
  SCOTLAND: REGIONS.EUROPE,
  BELGIUM: REGIONS.EUROPE,
  IPL: REGIONS.ASIA,
  SAUDIPL: REGIONS.ASIA,
  JLEAGUE: REGIONS.ASIA,
  AFL: REGIONS.OCEANIA,
  NRL: REGIONS.OCEANIA,
  ALEAGUE: REGIONS.OCEANIA,
  BBL: REGIONS.OCEANIA,
};
